### ISSUE TITLE
执行指令sd-switch报错

### ISSUE THREAD

**Issue by coderhyh** [MirrorCY/sd-switch#4]
## 执行指令报错

<img width="348" alt="313169C35B95F0B67E6964D90DD4C44A" src="https://github.com/user-attachments/assets/d0dbdc87-afe2-4ff6-8c96-5dd7f8f06e48">

## 配置

<img width="944" alt="F7A5F664065B1331CEE77C7098394FCF" src="https://github.com/user-attachments/assets/c0bec7c6-2bd0-4302-bfc1-7a61218840d5">

## 系统
macos 14.4.1

## 报错代码

logger插件是最新的
```
2024-07-19 10:19:08 [W] command sd-switch 
                        TypeError: Cannot read properties of null (reading 'logger')
                            at <anonymous> (/Users/coderhyh/Desktop/code/koishi-project/node_modules/@cordisjs/logger/src/index.ts:38:12)
                            at Object.apply (/Users/coderhyh/Desktop/code/koishi-project/node_modules/@cordisjs/core/src/reflect.ts:192:23)
                            at Proxy.dispatch (/Users/coderhyh/Desktop/code/koishi-project/node_modules/@cordisjs/core/src/events.ts:141:27)
                            at dispatch.next (<anonymous>)
                            at Function.from (<anonymous>)
                            at Proxy.emit (/Users/coderhyh/Desktop/code/koishi-project/node_modules/@cordisjs/core/src/events.ts:150:11)
                            at Proxy.axios (/Users/coderhyh/Desktop/code/koishi-project/node_modules/@koishijs/plugin-http/node_modules/@cordisjs/plugin-http/lib/index.cjs:373:12)
                            at Object.apply (/Users/coderhyh/Desktop/code/koishi-project/node_modules/@cordisjs/core/src/utils.ts:126:40)
                            at getInfo (/Users/coderhyh/Desktop/code/koishi-project/node_modules/koishi-plugin-sd-switch/lib/index.js:82:44)
                            at sendInfo (/Users/coderhyh/Desktop/code/koishi-project/node_modules/koishi-plugin-sd-switch/lib/index.js:102:19)
```

**Comment by MirrorCY** [comment]
好的，今晚确认

**Comment by MirrorCY** [comment]
![image](https://github.com/user-attachments/assets/e8f250ff-47bc-401c-af07-ff81f63143c7)
修了，试试？

**Comment by coderhyh** [comment]
> ![图像](https://private-user-images.githubusercontent.com/37006258/351060764-e8f250ff-47bc-401c-af07-ff81f63143c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MjQwOTcsIm5iZiI6MTcyMTcyMzc5NywicGF0aCI6Ii8zNzAwNjI1OC8zNTEwNjA3NjQtZThmMjUwZmYtNDdiYy00MDFjLWFmMDctZmY4MWY2MzE0M2M3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDA4MzYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3ZmI0YTdjOTViODVhZDBlMzZkYmY1Y2M5YmRhZjRkOTgyYzIyYTdhMTdiZmQ2MGJjMzk4YTkyMjYzMjdlOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m22TDGSSm9q3dD2rmDSlBUTFU62BpUBM0RtVzsGhQdY) 修改了一下，试试？

可以了 已经没问题了
